/**
 * MasterAgentBlock — orchestrator in a master/slave multi-agent setup.
 *
 * Unlike the plain `agent` block (single LLM call), MasterAgentBlock:
 *   1. Uses internal chain-of-thought to build a dynamic dispatch plan.
 *   2. Groups slaves into parallel execution layers (via the CoT plan).
 *   3. Dispatches slaves layer-by-layer (parallel within each layer).
 *   4. Optionally re-plans when a slave signals needs_clarification.
 *   5. Synthesises all slave outputs into one final_answer.
 *
 * Slaves are registered by dragging a slave_agent block onto this block on
 * the canvas (auto-registration via workspace-store.registerSlaveToMaster).
 *
 * Outputs:
 *   final_answer   — string  — synthesised answer incorporating all slave results
 *   slave_outputs  — json    — each slave's raw output keyed by slave_id
 *   cot_plan       — json    — the step-by-step plan the master generated
 *   confidence     — number  — 0–1 aggregate confidence from synthesis
 */
import { MasterAgentIcon } from '../../../components/icons'
import { getModelOptions, getDefaultModel, getProviderCredentialSubBlocks } from '../../utils'
import { defineCk8tBlock } from '../../ck8t-block-base.js'

export const MasterAgentBlock = defineCk8tBlock({
  type: 'master_agent',
  name: 'Master Agent',
  description: 'Orchestrate slave agents with chain-of-thought planning',
  longDescription:
    'The true orchestrator in a master/slave setup. Uses internal chain-of-thought ' +
    'reasoning to build a dispatch plan, fires registered slave agents in parallel ' +
    'or sequence according to the plan, and synthesises all outputs into a single ' +
    'cited final answer. Optionally re-plans when a slave flags needs_clarification.',
  bestPractices: `
  - Drag slave_agent blocks onto this block to register them.
  - The master auto-groups slaves by dependency — independent slaves run in parallel.
  - Enable "Adaptive Re-plan" for open-ended questions where slave outputs may surprise.
  - Wire final_answer downstream; inspect cot_plan + slave_outputs in trace view.
  `,
  category: 'blocks',
  bgColor: '#D97706',
  icon: MasterAgentIcon,
  tags: ['llm', 'orchestration', 'multi-agent', 'chain-of-thought', 'master-slave'],

  subBlocks: [
    {
      id: 'question',
      title: 'Question',
      type: 'long-input',
      placeholder: 'The complex question the swarm should answer…',
      rows: 3,
      required: true,
    },
    {
      id: 'context',
      title: 'Context',
      type: 'long-input',
      placeholder: 'Optional upstream data or background information…',
      rows: 3,
    },
    {
      id: 'model',
      title: 'Model (master + synthesis)',
      type: 'combobox',
      placeholder: 'Type or select a model...',
      required: true,
      get defaultValue() { return getDefaultModel() },
      options: getModelOptions,
    },
    {
      id: 'adaptiveRePlan',
      title: 'Adaptive Re-plan',
      type: 'switch',
      defaultValue: true,
      description:
        'If any slave returns needs_clarification=true, the master re-runs CoT ' +
        'with updated context and dispatches additional slave calls.',
    },
    {
      id: 'maxRePlanRounds',
      title: 'Max Re-plan Rounds',
      type: 'short-input',
      placeholder: '1',
      defaultValue: '1',
      mode: 'advanced',
      description: 'Maximum number of adaptive re-plan iterations (default 1).',
    },
    {
      id: 'synthesisPrompt',
      title: 'Synthesis Prompt Override',
      type: 'long-input',
      placeholder:
        'Leave blank to use the default synthesis prompt. ' +
        'Override only when you need domain-specific synthesis instructions.',
      rows: 3,
      mode: 'advanced',
    },
    ...getProviderCredentialSubBlocks(),
  ],

  inputs: {
    question: { type: 'string', description: 'Complex question for the swarm to answer' },
    context:  { type: 'json',   description: 'Optional background data from upstream blocks' },
  },

  outputs: {
    final_answer:  { type: 'string', description: 'Synthesised answer from all slave results' },
    slave_outputs: { type: 'json',   description: 'Each slave\'s raw output keyed by slave_id' },
    cot_plan:      { type: 'json',   description: 'Step-by-step dispatch plan generated by the master' },
    confidence:    { type: 'number', description: 'Aggregate confidence 0–1 from synthesis' },
  },
})
